#pragma once

#include <beaker/common.hpp>

namespace llvm
{
  class LLVMContext;
  class Module;
  class Type;
  class Value;
  class Function;
  class BasicBlock;
} // namespace llvm

namespace beaker
{
  class Function_context;

  /// Provides context for translating a single statement or expression.
  /// Subexpressions and substatements are recursive generated by establishing
  /// a new context.
  class Instruction_generator
  {
  public:
    Instruction_generator(Function_context& parent);

    // Context

    /// Returns the Beaker context.
    Context& get_beaker_context() const;

    /// Returns the LLVM context.
    llvm::LLVMContext* get_llvm_context() const;

    /// Returns the LLVM module.
    llvm::Module* get_llvm_module() const;

    /// Returns the LLVM function.
    llvm::Function* get_llvm_function() const;

    // Blocks

    /// Returns the current block.
    llvm::BasicBlock* get_current_block() const;

    /// Emits `b`, making it the current block.
    void emit_block(llvm::BasicBlock* b);

    // Generation

    /// Generates the corresponding type for `t`.
    llvm::Type* generate_type(const Type* t);

    /// Generates the corresponding type for `d`.
    llvm::Type* generate_type(const Typed_declaration* d);

    /// Recursively generate the sequence of instructions to compute `e`.
    void generate_expression(const Expression* e);

    /// Generate the sequence of statements for to execute `s`.
    void generate_statement(const Statement* s);

  private:
    /// The parent context.
    Function_context& m_parent;
  };

} // namespace beaker
